config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index", as: "homepage"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #room editor
  get '/room/new', to: 'room#new', as: 'new_room'
  post '/room', to: 'room#create', as: 'create_room' 

  #rooms
  get '/room', to: 'room#index', as: 'rooms'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
    def index
        @room = Room.all
    end

    def new
        @room = Room.new
    end

    def create 
        @room = Room.new()
            @room.accom_type = params[:room][:accom_type][:avail_date][:address_loc]

            if @room.valid? && @room.save
                redirect_to rooms_path
            else
                render :new
            end
        
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/home/index.html.erb
  <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div>
        </div>

        <hr>
        <h2>Room for Caring</h2>
<p>Community driven emergency accommodation</p>
<%= link_to 'List Room', new_room_path %>
<hr>

      </div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rfc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/dc7e8223e9.js" crossorigin="anonymous"></script>
    
  </head>

  <body>

  <header>
    <%= render "shared/topnav" %>
  </header>
          <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
          <%end%>

          <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
        <%end%>


        <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">ROOM FOR CARING</h1>
          <p>Search for community driven emergency accommodation in your area.</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">List a Room »</a>
          <a class="btn btn-info btn-lg" href="#" role="button">Search for Rooms »</a>
          <a class="btn btn-success btn-lg" href="#" role="button">Learn more »</a>
          </p>
        </div>
      </div>

    
    <%= yield %>
    </main>
    

    <%= render "shared/footer" %>
  </body>
</html>

app/views/room/index.html.erb
<h2>Room</h2>
<table class="container">
    <tr>
        <th> Accommodation type </th>
        <th> data </th>
        <th> data </th>
        <th> data </th>
    </tr>
    <% @room.each do |room| %>
    <tr>
        <td> <%= "#{room.accom_type}" %> </td>
        <td> <%= "#{room.room_description}" %> </td>
        <td> data </td>
        <td> data </td>
    </tr>
    <%end%>
    <tr>
        <th>something</th>
    </tr>



</table>

app/views/room/new.html.erb
<div class="container">
    <h2>List Your Room</h2>

    <%= form_with model: @room  do |form| %>

    <div class="row">
        <%# ACCOMMODATION TYPE radio button %>

        <div class="form-check, col-sm bg-info text-white pt-2">
            <h5>Type of Accommodation</h5>

            <%= form.radio_button :accom_type, 'house' %>
            <%= form.label :accom_type, "House"%>
            <br />

            <%= form.radio_button :accom_type, 'room' %>
            <%= form.label :accom_type, 'Room'%>
            <br />

            <%= form.radio_button :accom_type, 'couch' %>
            <%= form.label :accom_type, 'Couch'%>
            <br />

            <%= form.radio_button :accom_type, 'tent' %>
            <%= form.label :accom_type, 'Tent'%>
            <br />
        </div>

        <%# ACCOMMODATION DETAILS dropdown %>



        <div class="form-check bg-light col-md pt-2">
        <h5>Accommodation Details</h5>
            <select class="custom-select custom-select-lg mb-2">
                <option selected="0">Number of double beds</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
                <option value="3">Four</option>
                <option value="3">Five</option>
                <option value="3">Six</option>

            </select>

            <select class="custom-select custom-select-lg mb-2">
                <option selected="0">Number of single beds</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
                <option value="3">Four</option>
                <option value="3">Five</option>
                <option value="3">Six</option>

            </select>

            <select class="custom-select custom-select-lg mb-2">
                <option selected>How many people can stay?</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
                <option value="3">Four</option>
                <option value="3">Five</option>
                <option value="3">Six</option>

            </select>

            
        </div>
        <%# ACCOMMODATION SETTINGS checkboxes %>
        <div class="form-check, col-4 bg-dark text-white pt-2">
        <h5>Accommodation Settings</h5>
            <div class="form-check mt-2 mb-2">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        Allow Children
                    </label>
            </div>

            <div class="form-check mt-2 mb-2">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        Allow Pets
                    </label>
            </div>

            <div class="form-check mt-2 mb-2">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        Allow Unverified
                    </label>
            </div>

            <div class="form-check mt-2 mb-2">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        SMS Booking Notifications
                    </label>
            </div>

            <div class="form-check mt-2 mb-2">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        Allow Unverified
                    </label>
            </div>
        </div>
    </div>
    <div class="bg-light  pr-4 pl-4">
        <div class="row">
        <div class="form-group col-md">
            <label for="exampleFormControlTextarea1">Description</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Describe the room. If you have special conditions, please state them here."></textarea>
        </div>        
    

    

    <%# ACCOMMODATION DETAILS text area %>

    <%# ACCOMMODATION PHOTOS upload %>

    <%= form.submit "List Room", class: "btn btn-success mt-3" %>
    </div>
    <% end %>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer class="container">
      <p>© RoomForCaring 2020</p>
    </footer>

app/views/shared/_topnav.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top" style="background-color: #ffb266">
    <a class="navbar-brand" href="#"><i class="fas fa-door-open mr-sm-3"> </i>Room for Caring</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="room/find">Find Rooms</a>
            </li>
            <li class="nav-item">
                <%= link_to 'List Room', new_room_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/how-it-works">How it Works</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/faq">FAQ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="about">About</a>
            </li>
            <li class="nav-item">
                <% if user_signed_in? %>
                <%= link_to 'Log Out', destroy_user_session_path, method:"delete", class:"nav-link" %>
                <li class="nav-link"><%= current_user.email%></li>
                <% else %>
                <%= link_to 'Log In', new_user_session_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <% link_to "Sign Up", new_user_registration_path %>
                <%end%>
            </li>
        </ul>

        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-3" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>



    </div>
</nav>